spring:
  application:
    name: betgether-server

  datasource:
    url: jdbc:mysql://localhost:3306/betgether?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: betgether
    password: betgether_pw
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

jwt:
  secret: "kuit6secretkeykuit6secretkeykuit6secretkeykuit6secretkeykuit6secretkey"